stateDiagram-v2
    direction LR

    state if_start <<choice>>
    state if_resolved <<choice>>

    [*] --> Pending
    Pending --> if_start
    if_start --> Running : .then()
    if_start --> Running : .start()
    if_start --> Cancelled : [cancel]

    Running --> if_resolved
    if_resolved --> state=FULFILLED : task returns
    if_resolved --> state=REJECTED : task throws
    if_resolved --> Cancelled : [cancel]

    state=FULFILLED --> Fulfilled
    state=REJECTED --> Rejected
    
    Cancelled --> Rejected

    state Pending {
      [*] --> state=PENDING
      state=PENDING --> Wait_pending
      Wait_pending --> [*] : .then()
      Wait_pending --> [*] : .start()
      Wait_pending --> [*] : [cancel]
      Wait_pending : Wait
    }

    state Running {
      state if_pause <<choice>>
      state if_more <<choice>>
      state if_end <<choice>>

      [*] --> NotifyStarted
      NotifyStarted --> if_pause
      if_pause --> Run : pause = 0
      if_pause --> Paused : pause > 0
      Run --> if_more
      if_more --> Paused : pause > 0
      if_more --> Run : pause = 0
      if_more --> [*] : [rejected]
      if_more --> [*] : [fulfilled]
      Paused --> if_end
      if_end --> [*] : [rejected]
      if_end --> [*] : [fulfilled]
      if_end --> if_pause : pause = 0
      NotifyStarted : Notify onStart

      state Run {
        [*] --> state=RUNNING
        state=RUNNING --> Execute
        Execute --> [*] : [rejected]
        Execute --> [*] : [fulfilled]
        Execute --> [*] : [pause > 0]
        Execute : Execute task
      }

      state Paused {
        [*] --> state=PAUSED
        state=PAUSED --> Wait
        Wait --> [*] : pause = 0
        Wait --> [*] : [rejected]
        Wait --> [*] : [fulfilled]
      }
    }

    state Fulfilled {
      [*] --> NotifyFulfilled
      NotifyFulfilled --> [*]
      NotifyFulfilled : Notify onFullfilled
    }

    state Rejected {
      [*] --> NotifyRejected
      NotifyRejected --> [*]
      NotifyRejected : Notify onRejected
    }

    state Cancelled {
      [*] --> state=CANCELLED
      state=CANCELLED --> NotifyCancelled
      NotifyCancelled --> [*]
      NotifyCancelled : Notify onCancelled
    }
