stateDiagram-v2
    direction LR
    [*] --> Pending
    Pending --> Running : .then()
    Pending --> Running : .start()
    Running --> state=FULFILLED : computation returns
    state=FULFILLED --> Fulfilled
    Running --> state=REJECTED : computation throws
    state=REJECTED --> Rejected
    Running --> Timeout : timeout

    Pending --> Timeout : timeout
    Timeout --> Rejected
    Pending --> Cancelled : cancel
    Running --> Cancelled : cancel
    Cancelled --> Rejected

    state Pending {
      [*] --> state=PENDING
      state=PENDING --> Timer
      Timer --> [*]
      Timer : Start Timer
    }

     state Running {
      [*] --> state=RUNNING
      state=RUNNING --> NotifyStarted
      NotifyStarted --> Execute
      Execute --> [*]
      NotifyStarted : Notify onStart
    }

    state Fulfilled {
      [*] --> NotifyFulfilled
      NotifyFulfilled --> [*]
      NotifyFulfilled : Notify onFullfilled
    }

    state Rejected {
      [*] --> NotifyRejected
      NotifyRejected --> [*]
      NotifyRejected : Notify onRejected
    }

    state Timeout {
      [*] --> NotifyTimeout
      NotifyTimeout --> [*]
      NotifyTimeout : Notify onTimeout
    }

    state Cancelled {
      [*] --> state=CANCELLED
      state=CANCELLED --> NotifyCancelled
      NotifyCancelled --> [*]
      NotifyCancelled: Notif onCancelled
    }
